### obtener todos los users
GET http://localhost:3000/api/users

### ID
@id = {{crearUsuario.response.body.data.id}}

### obtener un user
GET http://localhost:3000/api/users/{{id}}

### CREAR un nuevo user
# @name crearUsuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "nombre": "Adrian",
    "apellido": "Meca",
    "dni": 35569423,
    "fechaNac": "1979-01-27T00:00:00.000Z",
    "username": "adrianmeca",
    "contraseña":"12345",
    "mail":"adrianmeca@gmail.com"
}

### MODIFICAR un user
PUT http://localhost:3000/api/users/{{id}}
Content-Type: application/json

{
    "nombre": "Lucas",
    "apellido": "Ramirez",
    "dni": 42589642,
    "fechaNac": "1979-01-27T00:00:00.000Z",
    "username": "luquiramirez",
    "contraseña":"67891",
    "mail":"luquiramirez@gmail.com"
}

### MODIFICAR un nuevo user parcial
PATCH  http://localhost:3000/api/users/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "username":"anabellegomez",
    "mail":"anagomez@hotmail.com"
}

### ELIMINAR un user 
DELETE http://localhost:3000/api/users/{{id}}
