### obtener todos las session types
GET http://localhost:3000/api/sessionTypes

### ID
@id = {{crearTipoSesion.response.body.data.id}}

### obtener una session
GET http://localhost:3000/api/sessionTypes/{{id}}

### CREAR una nueva session
# @name crearTipoSesion
POST http://localhost:3000/api/sessionTypes
Content-Type: application/json

{
    "nombreTipo" : "Pomodoro Corto",
    "tiempoFoco": 25,
    "recreoCorto": 5,
    "recreoLargo": 20
}

### MODIFICAR una session
PUT http://localhost:3000/api/sessionTypes/{{id}}
Content-Type: application/json

{
    "nombreTipo" : "Pomodoro Largo",
    "tiempoFoco": 60,
    "recreoCorto": 10,
    "recreoLargo": 25
}

# ### MODIFICAR una session parcialmente
# PATCH  http://localhost:3000/api/sessionTypes/3301d471-92e6-4fb5-886f-e98c24251f61 
# Content-Type: application/json

# {
#     "nombreTipo" : "Not Pomodoro"
# }

### ELIMINAR un user 
DELETE http://localhost:3000/api/sessionTypes/{{id}}
